name: wazzlitt
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  country_code_picker: ^3.0.0
  firebase_core: ^2.13.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  google_maps_flutter: ^2.2.8
  provider: ^6.0.5
  url_launcher: ^6.1.11
  image_picker: ^0.8.7+5
  share_plus: ^7.0.2
  intl: ^0.18.0
  location: ^5.0.0-dev.8
  shared_preferences: ^2.1.2
  google_fonts: ^5.0.0
  intl_phone_field: ^3.1.0
  geolocator: ^9.0.2
  animate_do: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
