name: wazzlitt
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  country_code_picker: any
  firebase_core: any
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: any
  google_maps_flutter: any
  provider: any
  url_launcher: any
  image_picker: any
  share_plus: any
  intl: any
  location: any
  shared_preferences: any
  intl_phone_field: any
  geolocator: any
  animate_do: any
  firebase_auth: any
  firebase_storage: any
  cloud_firestore: ^4.17.5
  pin_code_fields: any
  geocoding: any
  http: any
  cached_network_image: any
  uuid: any
  flutter_stripe: any
  cloud_functions: any
  flutter_dotenv: any
  geo_firestore_flutter: any
  geoflutterfire_updated: any
  google_places_autocomplete_text_field: any
  multi_trigger_autocomplete: any
  material_floating_search_bar_2: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
