// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOrc4Z3EPyqAkxw2G9N7v6dSMVfioeKWo',
    appId: '1:1016492729672:web:f3853471864f735de93f7d',
    messagingSenderId: '1016492729672',
    projectId: 'wazzlitt-d7c47',
    authDomain: 'wazzlitt-d7c47.firebaseapp.com',
    storageBucket: 'wazzlitt-d7c47.appspot.com',
    measurementId: 'G-8RJWNFSY6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2MbK7XyM12YhUyN2y8c3f3NmN8OuAl_o',
    appId: '1:1016492729672:android:45fbca4d9f1dd744e93f7d',
    messagingSenderId: '1016492729672',
    projectId: 'wazzlitt-d7c47',
    storageBucket: 'wazzlitt-d7c47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'MAPS_API_KEY',
    appId: '1:1016492729672:ios:aab3b965fbc4da45e93f7d',
    messagingSenderId: '1016492729672',
    projectId: 'wazzlitt-d7c47',
    storageBucket: 'wazzlitt-d7c47.appspot.com',
    iosClientId:
        '1016492729672-o3lv3p935f2qqpjmuc1cn35v7kc8bhbd.apps.googleusercontent.com',
    iosBundleId: 'com.example.wazzlitt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'MAPS_API_KEY',
    appId: '1:1016492729672:ios:6b76ce4928d056d2e93f7d',
    messagingSenderId: '1016492729672',
    projectId: 'wazzlitt-d7c47',
    storageBucket: 'wazzlitt-d7c47.appspot.com',
    iosClientId:
        '1016492729672-8esb0cdt3rva9i5ej9d44p5cd2v3tdd5.apps.googleusercontent.com',
    iosBundleId: 'com.example.wazzlitt.RunnerTests',
  );
}
